# Path: ./docker-compose.yml

version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  api:
    user: "1000:1000"
    container_name: project_x_api
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.localhost`)"
    networks:
      - my_network

  db:
    image: postgres:15-alpine
    container_name: project_x_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - my_network

  traefik:
    image: traefik:v2.9.6
    container_name: project_x_traefik
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - my_network

  test:
    container_name: project_x_test
    env_file:
      - .env.test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    networks:
      - my_network
    depends_on:
      - api

volumes:
  postgres_data:
