# Utiliza la misma imagen base que tu aplicación
FROM python:3.11.1-slim as base

# Configura el entorno como lo haces en tu Dockerfile original
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Configura el directorio de trabajo
WORKDIR /app

RUN apt-get update && apt-get install -y curl

# Instala Poetry y las dependencias como en tu Dockerfile original
RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN pip install pytest-watch


# Copia solo los archivos necesarios para instalar las dependencias
COPY pyproject.toml poetry.lock ./

# Instala todas las dependencias, incluso las de desarrollo (para las pruebas)
RUN poetry install

# Copia el código fuente de la aplicación y las pruebas
COPY . .

# Copia el script de espera al contenedor
COPY wait_for_api.sh /wait_for_api.sh
RUN chmod +x /wait_for_api.sh

# Cambia el CMD para usar el script de espera antes de ejecutar las pruebas
CMD ["/wait_for_api.sh", "http://api:8000/v1/ping/", "ptw"]

